// <auto-generated />
using System;
using HOVLaneViolation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250731223517_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("HOVLaneViolation.Entities.HOVCustomerData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HOVCustomers");
                });

            modelBuilder.Entity("HOVLaneViolation.Entities.HOVMasterData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("HOVMasters");
                });

            modelBuilder.Entity("HOVLaneViolation.Entities.HOVRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("HOVRules");
                });

            modelBuilder.Entity("HOVLaneViolation.Entities.HOVTransactionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HOVCustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HOVMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ViolationStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HOVCustomerId");

                    b.HasIndex("HOVMasterId");

                    b.ToTable("HOVTransactions");
                });

            modelBuilder.Entity("HOVLaneViolation.Entities.HOVTransactionData", b =>
                {
                    b.HasOne("HOVLaneViolation.Entities.HOVCustomerData", "HOVCustomer")
                        .WithMany()
                        .HasForeignKey("HOVCustomerId");

                    b.HasOne("HOVLaneViolation.Entities.HOVMasterData", "HOVMaster")
                        .WithMany()
                        .HasForeignKey("HOVMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HOVCustomer");

                    b.Navigation("HOVMaster");
                });
#pragma warning restore 612, 618
        }
    }
}
